name: Bun Tests

on:
  push:
  workflow_dispatch:

jobs:
  test:
    name: "Bun Tests"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - run: bun install
      - run: bun test
